server:
  port: ${BACKEND_PORT:8080}
  servlet:
    context-path: /api
# 数据库配置
spring:
#  可以指定环境
#  profiles:
#    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATABASE_HOST:}:${DATABASE_PORT:}/${DATABASE_NAME:}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}

security:
  jwt:
    secret: ${JWT_SECRET:}
    expirationDays: 7

mybatis:
  mapper-locations: classpath:/database/mapper/*.xml
  type-aliases-package: com.yupi.yuhaigui.database.model
# 接口文档
knife4j:
  enable: true
  openapi:
    title: 鱼皮的接口文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.yupi.yuhaigui.controller
# 接入 AI 大模型
ai:
  apiKey: ${AI_API_KEY:}
  baseUrl: ${AI_BASE_URL:}
  model: ${AI_MODEL:}